name: sata_widgets
description: This plugin created by company SATA_SOFTWARE
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  localstore: ^1.2.0
  flutter_translate: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: uz.sata.sata_widgets
        pluginClass: SataWidgetsPlugin
      ios:
        pluginClass: SataWidgetsPlugin
